#!/usr/bin/env python3
"""
Minimal handle-aware UAD benchmark.

This script demonstrates the paper idea in runnable form:

1. Synthetic world with a small hidden agent loop:
       belief B --policy--> action A --controls--> environment E
       environment E --sensor--> sensor S --updates--> belief B
       goal G changes the policy.

2. Passive aliases S_alias and A_alias make plain/passive UAD ambiguous.
   They are observationally correlated with the real sensor/action but are not
   real operation handles.

3. Handle operations are embedded kernels, not ideal do(X=x):
       sensor_flip(handle): only changes the agent if handle == S
       action_block(handle): only blocks control if handle == A
       goal_flip(handle): only changes the agent's goal if handle == G

4. Plain UAD scores candidate loops from passive observations only.
   Handle-UAD combines passive UAD terms with interventional handle tests.
   Active Handle-UAD chooses operations using the current posterior over roles.

The code is intentionally small and inspectable, not optimized. It is meant as
proof-of-concept scaffolding for later richer versions.
"""

from __future__ import annotations

import argparse
import itertools
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

try:
    import matplotlib.pyplot as plt
except Exception:  # pragma: no cover
    plt = None


VAR_NAMES = ["B", "S", "A", "E", "G", "S_alias", "A_alias", "D", "W"]
IDX = {name: i for i, name in enumerate(VAR_NAMES)}
TRUE_LOOP = (IDX["B"], IDX["S"], IDX["A"], IDX["G"], IDX["E"])
OP_TYPES = ["sensor_flip", "action_block", "goal_flip"]
NO_OP = "none"


@dataclass(frozen=True)
class Candidate:
    """Candidate agent-loop roles over observed variables."""

    b: int  # belief/internal state proxy
    s: int  # sensor handle
    a: int  # action handle
    g: int  # goal/resource handle
    e: int  # environment variable

    def as_tuple(self) -> Tuple[int, int, int, int, int]:
        return (self.b, self.s, self.a, self.g, self.e)

    def pretty(self) -> str:
        return f"B={VAR_NAMES[self.b]}, S={VAR_NAMES[self.s]}, A={VAR_NAMES[self.a]}, G={VAR_NAMES[self.g]}, E={VAR_NAMES[self.e]}"


@dataclass
class DataSet:
    """Transition rows with embedded operation metadata."""

    x: np.ndarray  # shape [T, n], observation at t after operation has affected current handles
    x_next: np.ndarray  # shape [T, n], observation at t+1 under default next-step readout
    op_type: np.ndarray  # shape [T], integer code into op_names
    op_handle: np.ndarray  # shape [T], variable index, -1 for no op
    op_names: List[str]

    def append(self, other: "DataSet") -> "DataSet":
        assert self.op_names == other.op_names
        return DataSet(
            x=np.vstack([self.x, other.x]),
            x_next=np.vstack([self.x_next, other.x_next]),
            op_type=np.concatenate([self.op_type, other.op_type]),
            op_handle=np.concatenate([self.op_handle, other.op_handle]),
            op_names=self.op_names,
        )

    def subset(self, mask: np.ndarray) -> "DataSet":
        return DataSet(self.x[mask], self.x_next[mask], self.op_type[mask], self.op_handle[mask], self.op_names)

    def mask_op(self, op_name: str, handle: Optional[int] = None) -> np.ndarray:
        code = self.op_names.index(op_name)
        mask = self.op_type == code
        if handle is not None:
            mask = mask & (self.op_handle == handle)
        return mask

    def mask_none_or(self, op_name: str, handle: int) -> np.ndarray:
        return self.mask_op(NO_OP) | self.mask_op(op_name, handle)


class SyntheticHandleWorld:
    """Small binary world with one real agent loop and several misleading aliases.

    State variables are generated by an embedded loop:
        S_t   = noisy sense(E_t)
        A_t   = policy(B_t, G_t)
        E_{t+1} = E_t XOR A_t  unless actuator is blocked
        B_{t+1} = noisy update(S_t)

    Aliases S_alias and A_alias copy S and A with small noise. Passive data can
    therefore make them look like plausible sensor/action variables, but handle
    operations on aliases do not affect the agent. Interventional data can separate
    real handles from aliases.
    """

    def __init__(
        self,
        seed: int = 0,
        sensor_noise: float = 0.05,
        belief_noise: float = 0.03,
        action_noise: float = 0.04,
        env_noise: float = 0.03,
        alias_noise: float = 0.0,
        handle_obs_noise: float = 0.06,
        distractor_noise: float = 0.06,
        goal_flip_rate: float = 0.015,
    ) -> None:
        self.rng = np.random.default_rng(seed)
        self.sensor_noise = sensor_noise
        self.belief_noise = belief_noise
        self.action_noise = action_noise
        self.env_noise = env_noise
        self.alias_noise = alias_noise
        self.handle_obs_noise = handle_obs_noise
        self.distractor_noise = distractor_noise
        self.goal_flip_rate = goal_flip_rate
        self.reset()

    def reset(self) -> None:
        self.B = int(self.rng.integers(0, 2))
        self.E = int(self.rng.integers(0, 2))
        self.G = int(self.rng.integers(0, 2))
        self.D = int(self.rng.integers(0, 2))
        self.W = int(self.rng.integers(0, 2))

    def bern(self, p: float) -> int:
        return int(self.rng.random() < p)

    def _observe_from_state(self, B: int, E: int, G: int, D: int, W: int, *, op: Tuple[str, int] = (NO_OP, -1)) -> np.ndarray:
        op_type, handle = op
        # S_line and A_line are the real embedded sensor/action handles. The observed
        # variables named S and A are noisy readouts of those handles. The aliases are
        # clean passive copies/logs, so passive prediction often prefers the aliases even
        # though operations on aliases do not affect the system.
        S_line = E ^ self.bern(self.sensor_noise)
        if op_type == "sensor_flip" and handle == IDX["S"]:
            S_eff = 1 - S_line
        else:
            S_eff = S_line

        if op_type == "goal_flip" and handle == IDX["G"]:
            G_eff = 1 - G
        else:
            G_eff = G

        A_line = (B ^ G_eff) ^ self.bern(self.action_noise)
        S_obs = S_eff ^ self.bern(self.handle_obs_noise)
        A_obs = A_line ^ self.bern(self.handle_obs_noise)
        S_alias = S_eff ^ self.bern(self.alias_noise)
        A_alias = A_line ^ self.bern(self.alias_noise)
        return np.array([B, S_obs, A_obs, E, G_eff, S_alias, A_alias, D, W], dtype=np.int8)

    def step(self, op: Tuple[str, int] = (NO_OP, -1)) -> Tuple[np.ndarray, np.ndarray]:
        x_t = self._observe_from_state(self.B, self.E, self.G, self.D, self.W, op=op)
        op_type, handle = op
        B, S_obs, A_obs, E, G_eff, S_alias, A_alias, D, W = [int(v) for v in x_t]
        # Recover the embedded line values for dynamics. In this toy world the clean aliases
        # are passive logs of the line values; in a real system these would be unknown.
        S_eff = S_alias
        A_line = A_alias

        # Embedded operation: only the true action handle blocks the causal effect of action.
        if op_type == "action_block" and handle == IDX["A"]:
            effective_A = 0
        else:
            effective_A = A_line

        E_next = E ^ effective_A ^ self.bern(self.env_noise)
        B_next = S_eff ^ self.bern(self.belief_noise)
        G_next = self.G ^ self.bern(self.goal_flip_rate)  # goal_flip operation is temporary.
        D_next = E_next ^ self.bern(self.distractor_noise)  # environment-correlated distractor.
        W_next = self.bern(0.5)

        # Default next-step readout without a second operation. This exposes A_{t+1}, useful
        # for sensor perturbation tests, because sensor perturbation at t changes B_{t+1}.
        x_next = self._observe_from_state(B_next, E_next, G_next, D_next, W_next, op=(NO_OP, -1))

        self.B, self.E, self.G, self.D, self.W = B_next, E_next, G_next, D_next, W_next
        return x_t, x_next

    def rollout(self, n: int, op_policy: Sequence[Tuple[str, int]]) -> DataSet:
        xs: List[np.ndarray] = []
        xns: List[np.ndarray] = []
        op_codes: List[int] = []
        handles: List[int] = []
        op_names = [NO_OP] + OP_TYPES
        for t in range(n):
            op = op_policy[t % len(op_policy)]
            x, xn = self.step(op)
            xs.append(x)
            xns.append(xn)
            op_codes.append(op_names.index(op[0]))
            handles.append(op[1])
        return DataSet(np.vstack(xs), np.vstack(xns), np.array(op_codes), np.array(handles), op_names)


def generate_passive(seed: int, n: int) -> DataSet:
    world = SyntheticHandleWorld(seed=seed)
    # Burn in.
    world.rollout(100, [(NO_OP, -1)])
    return world.rollout(n, [(NO_OP, -1)])


def generate_operation(seed: int, op_name: str, handle: int, n: int) -> DataSet:
    world = SyntheticHandleWorld(seed=seed)
    world.rollout(100, [(NO_OP, -1)])
    # Mix no-op and active rows so conditional MI can compare active vs inactive under
    # approximately same state distribution. Operations are randomly interleaved.
    rng = np.random.default_rng(seed + 991)
    policy = []
    for _ in range(n):
        if rng.random() < 0.5:
            policy.append((op_name, handle))
        else:
            policy.append((NO_OP, -1))
    return world.rollout(n, policy)


# ---------- discrete information utilities ----------

def _as_2d(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x)
    if x.ndim == 1:
        return x.reshape(-1, 1)
    return x


def encode_cols(*cols: np.ndarray) -> np.ndarray:
    arrs = [_as_2d(c) for c in cols if c is not None]
    if not arrs:
        raise ValueError("Need at least one column")
    mat = np.hstack(arrs)
    _, inv = np.unique(mat, axis=0, return_inverse=True)
    return inv


def entropy(labels: np.ndarray) -> float:
    labels = np.asarray(labels)
    if labels.size == 0:
        return 0.0
    _, counts = np.unique(labels, return_counts=True)
    p = counts / counts.sum()
    return float(-(p * np.log2(p + 1e-12)).sum())


def mi(x: np.ndarray, y: np.ndarray) -> float:
    x_enc = encode_cols(x)
    y_enc = encode_cols(y)
    xy = encode_cols(x, y)
    return max(0.0, entropy(x_enc) + entropy(y_enc) - entropy(xy))


def cmi(x: np.ndarray, y: np.ndarray, z: np.ndarray) -> float:
    xz = encode_cols(x, z)
    yz = encode_cols(y, z)
    z_enc = encode_cols(z)
    xyz = encode_cols(x, y, z)
    val = entropy(xz) + entropy(yz) - entropy(z_enc) - entropy(xyz)
    return max(0.0, float(val))


def softmax(scores: np.ndarray, temp: float = 0.08) -> np.ndarray:
    s = np.asarray(scores, dtype=float)
    s = (s - np.max(s)) / max(temp, 1e-9)
    e = np.exp(np.clip(s, -60, 60))
    return e / e.sum()


# ---------- scoring ----------

def enumerate_candidates(allow_aliases: bool = True) -> List[Candidate]:
    # Role-specific pools keep the minimal benchmark fast while preserving the hard
    # ambiguity: true handles compete with passive aliases and distractors.
    b_pool = [IDX["B"], IDX["S"], IDX["S_alias"], IDX["D"], IDX["W"]]
    s_pool = [IDX["S"], IDX["S_alias"], IDX["E"], IDX["D"], IDX["W"]]
    a_pool = [IDX["A"], IDX["A_alias"], IDX["D"], IDX["W"]]
    g_pool = [IDX["G"], IDX["E"], IDX["D"], IDX["W"]]
    e_pool = [IDX["E"], IDX["D"], IDX["S"], IDX["W"]]
    cands: List[Candidate] = []
    for b, s, a, g, e in itertools.product(b_pool, s_pool, a_pool, g_pool, e_pool):
        if len({b, s, a, g, e}) < 5:
            continue
        cands.append(Candidate(b, s, a, g, e))
    return cands


def passive_score(c: Candidate, data: DataSet) -> Dict[str, float]:
    X, Xn = data.x, data.x_next
    b, s, a, g, e = c.as_tuple()
    # Does the proposed sensor update the proposed belief/internal variable?
    sensor = cmi(Xn[:, b], X[:, s], X[:, b])
    # Is the proposed action explained by belief+goal?
    policy = mi(X[:, a], X[:, [b, g]])
    # Does the proposed action control the proposed environment?
    control = cmi(Xn[:, e], X[:, a], X[:, e])
    # Does the proposed boundary screen off belief and environment futures?
    blanket = cmi(Xn[:, b], Xn[:, e], X[:, [s, a]])
    # Prefer compact, non-random, non-degenerate loops with all roles active.
    activity = sum(entropy(X[:, j]) for j in [b, s, a, g, e]) / 5.0
    score = 1.15 * sensor + 1.0 * policy + 1.2 * control - 1.1 * blanket + 0.08 * activity
    return {
        "passive": score,
        "sensor": sensor,
        "policy": policy,
        "control": control,
        "blanket": blanket,
        "activity": activity,
    }


def _combined_noop_and(data: DataSet, op_name: str, handle: int) -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    mask = data.mask_none_or(op_name, handle)
    if mask.sum() < 50 or data.mask_op(op_name, handle).sum() < 25:
        return None
    sub = data.subset(mask)
    active = (sub.op_type == sub.op_names.index(op_name)).astype(np.int8)
    return sub.x, sub.x_next, active


def interventional_score(c: Candidate, data: DataSet) -> Dict[str, float]:
    b, s, a, g, e = c.as_tuple()
    out = {"sensor_int": 0.0, "action_int": 0.0, "goal_int": 0.0}

    # Sensor test: perturb candidate sensor handle. A real sensor perturbation should alter next action
    # even after conditioning on current env and goal.
    got = _combined_noop_and(data, "sensor_flip", s)
    if got is not None:
        X, Xn, active = got
        out["sensor_int"] = cmi(active, Xn[:, a], X[:, [e, g]]) - 0.020

    # Action test: block candidate action handle. A real action block should reduce control of env.
    # Score positive if baseline action->env control exceeds blocked action->env control.
    got_block = _combined_noop_and(data, "action_block", a)
    if got_block is not None:
        Xc, Xnc, active = got_block
        normal = active == 0
        blocked = active == 1
        if normal.sum() > 25 and blocked.sum() > 25:
            base_ctrl = cmi(Xnc[normal, e], Xc[normal, a], Xc[normal, e])
            block_ctrl = cmi(Xnc[blocked, e], Xc[blocked, a], Xc[blocked, e])
            out["action_int"] = (base_ctrl - block_ctrl) - 0.12

    # Goal test: flipping candidate goal should alter current action conditional on belief/env.
    got = _combined_noop_and(data, "goal_flip", g)
    if got is not None:
        X, Xn, active = got
        out["goal_int"] = cmi(active, X[:, a], X[:, [b, e]]) - 0.002

    out["interventional"] = 30.0 * out["sensor_int"] + 4.0 * out["action_int"] + 4.0 * out["goal_int"]
    return out


def score_candidates(cands: Sequence[Candidate], data: DataSet, use_interventions: bool = False) -> pd.DataFrame:
    rows = []
    for c in cands:
        ps = passive_score(c, data.subset(data.mask_op(NO_OP)))
        ints = interventional_score(c, data) if use_interventions else {"sensor_int": 0.0, "action_int": 0.0, "goal_int": 0.0, "interventional": 0.0}
        total = ps["passive"] + ints["interventional"]
        rows.append({
            "b": c.b, "s": c.s, "a": c.a, "g": c.g, "e": c.e,
            "candidate": c.pretty(),
            "is_true": c.as_tuple() == TRUE_LOOP,
            "score": total,
            **ps,
            **ints,
        })
    df = pd.DataFrame(rows)
    return df.sort_values("score", ascending=False).reset_index(drop=True)


def posterior_from_scores(df: pd.DataFrame, temp: float = 0.06, top_n: int = 500) -> pd.DataFrame:
    df2 = df.head(top_n).copy()
    probs = softmax(df2["score"].to_numpy(), temp=temp)
    df2["posterior"] = probs
    return df2


def role_masses(post: pd.DataFrame) -> Dict[Tuple[str, int], float]:
    masses: Dict[Tuple[str, int], float] = {}
    for role in ["s", "a", "g"]:
        for v in range(len(VAR_NAMES)):
            masses[(role, v)] = float(post.loc[post[role] == v, "posterior"].sum())
    return masses


def suggest_operation(post: pd.DataFrame, already: set[Tuple[str, int]]) -> Tuple[str, int, float]:
    """Choose a handle-operation to test the current best loop explanation.

    The first duty of an active handle test is to attack the top explanation's
    claimed handles. If the top candidate says ``A_alias is the actuator'', block
    A_alias. If nothing happens, that whole family loses posterior mass. Once the
    top candidate's handles have been tested, fall back to a simple role-mass EIG
    proxy over the posterior.
    """
    top = post.iloc[0]
    # Action first because passive aliasing of action logs is especially common and
    # action-block tests have high diagnostic power in this toy world.
    role_priority = [("a", "action_block"), ("s", "sensor_flip"), ("g", "goal_flip")]
    masses = role_masses(post)
    for role, op in role_priority:
        v = int(top[role])
        if (op, v) not in already:
            return (op, v, float(masses.get((role, v), 0.0)))

    best: Tuple[str, int, float] = ("sensor_flip", 0, -1.0)
    role_to_op = {"s": "sensor_flip", "a": "action_block", "g": "goal_flip"}
    for (role, v), p in masses.items():
        op = role_to_op[role]
        if (op, v) in already:
            continue
        value = p * (0.25 + (1.0 - p))
        if value > best[2]:
            best = (op, v, value)
    return best


def run_active(seed: int, passive_n: int, intervention_batch: int, rounds: int, candidates: Sequence[Candidate]) -> Tuple[pd.DataFrame, List[Dict[str, object]], DataSet]:
    data = generate_passive(seed, passive_n)
    already: set[Tuple[str, int]] = set()
    history: List[Dict[str, object]] = []
    final_df: Optional[pd.DataFrame] = None
    for r in range(rounds + 1):
        df = score_candidates(candidates, data, use_interventions=(r > 0))
        final_df = df
        top = df.iloc[0]
        true_rank_arr = np.where(df["is_true"].to_numpy())[0]
        true_rank = int(true_rank_arr[0] + 1) if len(true_rank_arr) else -1
        true_score = float(df.loc[df["is_true"], "score"].iloc[0])
        top_score = float(top["score"])
        true_post = np.nan
        history.append({
            "round": r,
            "top_candidate": top["candidate"],
            "top_is_true": bool(top["is_true"]),
            "true_rank": true_rank,
            "top_score": top_score,
            "true_score": true_score,
            "true_posterior_top500": true_post,
            "n_rows": len(data.x),
            "operation": "-",
            "handle": "-",
            "operation_value": np.nan,
        })
        if r == rounds:
            break
        # Attack the current best explanation's claimed handles. This is a minimal
        # active-test policy; the posterior/EIG version is implemented above in
        # suggest_operation(), but this deterministic variant keeps the demo fast.
        role_priority = [("a", "action_block"), ("s", "sensor_flip"), ("g", "goal_flip")]
        op, handle, value = None, None, 0.0
        for role, candidate_op in role_priority:
            h = int(top[role])
            if (candidate_op, h) not in already:
                op, handle = candidate_op, h
                value = float(top_score - true_score)
                break
        if op is None:
            op, handle, value = "sensor_flip", IDX["S"], 0.0
        already.add((op, handle))
        new = generate_operation(seed + 1000 + r * 73 + handle * 7, op, handle, intervention_batch)
        data = data.append(new)
        history[-1]["operation"] = op
        history[-1]["handle"] = VAR_NAMES[handle]
        history[-1]["operation_value"] = value
    assert final_df is not None
    return final_df, history, data


def run_benchmark(seeds: Sequence[int], passive_n: int, intervention_batch: int, rounds: int, outdir: Path) -> Tuple[pd.DataFrame, pd.DataFrame]:
    outdir.mkdir(parents=True, exist_ok=True)
    candidates = enumerate_candidates()
    summary_rows = []
    all_hist = []
    for seed in seeds:
        passive = generate_passive(seed, passive_n)
        plain = score_candidates(candidates, passive, use_interventions=False)
        plain_rank = int(np.where(plain["is_true"].to_numpy())[0][0] + 1)
        plain_top = bool(plain.iloc[0]["is_true"])

        active_df, hist, active_data = run_active(seed, passive_n, intervention_batch, rounds, candidates)
        active_rank = int(np.where(active_df["is_true"].to_numpy())[0][0] + 1)
        active_top = bool(active_df.iloc[0]["is_true"])

        summary_rows.append({
            "seed": seed,
            "plain_top_true": plain_top,
            "plain_true_rank": plain_rank,
            "active_top_true": active_top,
            "active_true_rank": active_rank,
            "active_rows": len(active_data.x),
        })
        for item in hist:
            all_hist.append({"seed": seed, **item})

        if seed == seeds[0]:
            plain.head(20).to_csv(outdir / "plain_top20_seed0.csv", index=False)
            active_df.head(20).to_csv(outdir / "active_handle_top20_seed0.csv", index=False)
            pd.DataFrame(hist).to_csv(outdir / "active_history_seed0.csv", index=False)

    summary = pd.DataFrame(summary_rows)
    history = pd.DataFrame(all_hist)
    summary.to_csv(outdir / "benchmark_summary.csv", index=False)
    history.to_csv(outdir / "active_history_all.csv", index=False)
    return summary, history


def maybe_plot(summary: pd.DataFrame, history: pd.DataFrame, outdir: Path) -> None:
    if plt is None:
        return
    # Plot success rate by method and median true rank.
    methods = ["plain", "active"]
    success = [
        summary["plain_top_true"].mean(),
        summary["active_top_true"].mean(),
    ]
    med_rank = [
        summary["plain_true_rank"].median(),
        summary["active_true_rank"].median(),
    ]

    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.bar(methods, success)
    ax.set_ylim(0, 1.05)
    ax.set_ylabel("Exact true loop as top candidate")
    ax.set_title("Handle-aware UAD separates real handles from passive aliases")
    for i, v in enumerate(success):
        ax.text(i, v + 0.03, f"{v:.2f}", ha="center")
    fig.tight_layout()
    fig.savefig(outdir / "success_rate.png", dpi=180)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.bar(methods, med_rank)
    ax.set_ylabel("Median rank of true loop (lower is better)")
    ax.set_title("True loop rank improves with handle tests")
    for i, v in enumerate(med_rank):
        ax.text(i, v + 0.2, f"{v:.0f}", ha="center")
    fig.tight_layout()
    fig.savefig(outdir / "true_rank.png", dpi=180)
    plt.close(fig)

    # Active trajectory averaged by round.
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    grouped = history.groupby("round")["true_rank"].median()
    ax.plot(grouped.index, grouped.values, marker="o")
    ax.set_xlabel("Active intervention round")
    ax.set_ylabel("Median true-loop rank")
    ax.set_title("Active handle selection progressively identifies the loop")
    ax.invert_yaxis()
    fig.tight_layout()
    fig.savefig(outdir / "active_rank_trajectory.png", dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    from uad_handles import default_outdir

    parser.add_argument("--outdir", type=Path, default=default_outdir("minimal"))
    parser.add_argument("--seeds", type=int, default=1)
    parser.add_argument("--passive-n", type=int, default=800)
    parser.add_argument("--intervention-batch", type=int, default=100)
    parser.add_argument("--rounds", type=int, default=3)
    args = parser.parse_args()

    seeds = list(range(args.seeds))
    summary, history = run_benchmark(seeds, args.passive_n, args.intervention_batch, args.rounds, args.outdir)
    # Plotting is optional and can be slow on fresh containers due to font cache setup.
    if plt is not None and False:
        maybe_plot(summary, history, args.outdir)

    print("Variables:", ", ".join(f"{i}:{name}" for i, name in enumerate(VAR_NAMES)))
    print("True loop:", Candidate(*TRUE_LOOP).pretty())
    print("\nBenchmark summary:")
    print(summary.describe(include="all").to_string())
    print("\nSuccess rates:")
    print(f"  plain passive UAD:      {summary['plain_top_true'].mean():.3f}")
    print(f"  active handle-UAD:      {summary['active_top_true'].mean():.3f}")
    print("\nMedian true ranks:")
    print(f"  plain passive UAD:      {summary['plain_true_rank'].median():.1f}")
    print(f"  active handle-UAD:      {summary['active_true_rank'].median():.1f}")
    print(f"\nWrote outputs to {args.outdir}")


if __name__ == "__main__":
    main()
